site_name: Odilia Screen Reader
site_url: https://yggdrasil-sr.github.io
site_author: The Odilia contributors
copyright: Copyright © 2021 the Odilia contributors
site_description: |
  A modern, feature-rich screen reader for the Linux desktop, built in Rust.

repo_url: https://github.com/yggdrasil-sr/site
edit_uri: edit/main/docs/
remote_branch: main

nav:
  - Home: index.md
  - Design: design-document.md
  - Code: https://github.com/yggdrasil-sr

markdown_extensions:
  - def_list
  - codehilite
  - sane_lists
  - smarty
  - toc:
      permalink: True
